/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.sistemaintegramind.Model.entidades.Enumeradores;

public enum TipoDocumentoPaciente {

    AVALIACAO_PSICOLOGICA,
    LAUDO_PSICOLOGICO,
    RELATORIO_PSICOLOGICO,
    PARECER_PSICOLOGICO,
    ATESTADO_PSICOLOGICO,
    DECLARACAO_PSICOLOGICA,
    ENTREVISTA_PSICOLOGICA,
    ANAMNESE,
    PLANO_TERAPEUTICO,
    EVOLUCAO_CLINICA,
    REGISTRO_SESSAO,
    AVALIACAO_COMPORTAMENTAL,
    AVALIACAO_COGNITIVA,
    AVALIACAO_EMOCIONAL,
    AVALIACAO_NEUROPSICOLOGICA,
    RESULTADO_TESTE_PSICOLOGICO,
    DEVOLUTIVA_PSICOLOGICA,
    ENCAMINHAMENTO_PSICOLOGICO,
    ENCAMINHAMENTO_MEDICO,
    PLANO_TRATAMENTO,

    LAUDO_MEDICO,
    RELATORIO_MEDICO,
    ATESTADO_MEDICO,
    RECEITA_MEDICA,
    EXAME_MEDICO,
    EXAME_LABORATORIAL,
    EXAME_IMAGEM,
    RELATORIO_PSIQUIATRICO,
    LAUDO_PSIQUIATRICO,
    ENCAMINHAMENTO_OUTRO_PROFISSIONAL,

    DOCUMENTO_PESSOAL,
    RG,
    CPF,
    CNH,
    CERTIDAO_NASCIMENTO,
    CERTIDAO_CASAMENTO,
    COMPROVANTE_ENDERECO,
    CARTEIRA_TRABALHO,
    DOCUMENTO_RESPONSAVEL,
    DOCUMENTO_ESCOLAR,

    CONTRATO_PRESTACAO_SERVICOS,
    TERMO_CONSENTIMENTO,
    TERMO_RESPONSABILIDADE,
    TERMO_AUTORIZACAO,
    AUTORIZACAO_USO_IMAGEM,
    FICHA_CADASTRAL,
    COMPROVANTE_PAGAMENTO,
    DECLARACAO_PACIENTE,
    DOCUMENTO_JUDICIAL,
    OUTRO_DOCUMENTO
}