/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.sistemaintegramind.Model.entidades.Enumeradores;

/**
 *
 * @author Micro
 */
public enum TipoAtendimento {

    PRIMEIRA_CONSULTA,
    SESSAO_DE_ACOMPANHAMENTO,
    SESSAO_DE_PSICOTERAPIA,
    CONSULTA_DE_RETORNO,
    AVALIACAO_PSICOLOGICA,
    ENTREVISTA_PSICOLOGICA,
    ORIENTACAO_PSICOLOGICA,
    ACONSELHAMENTO_PSICOLOGICO,
    PSICOEDUCACAO,
    SESSAO_DE_ACOMPANHAMENTO_INFANTIL,
    SESSAO_DE_ACOMPANHAMENTO_DE_ADOLESCENTE,
    SESSAO_DE_ACOMPANHAMENTO_DE_ADULTO,
    SESSAO_DE_ACOMPANHAMENTO_DE_CASAL,
    SESSAO_DE_ACOMPANHAMENTO_FAMILIAR,
    ATENDIMENTO_PSICOLOGICO_DE_EMERGENCIA,
    ATENDIMENTO_PSICOLOGICO_BREVE,
    SESSAO_DE_REAVALIACAO,
    DEVOLUTIVA_DA_AVALIACAO_PSICOLOGICA,
    ORIENTACAO_AOS_RESPONSAVEIS,
    ENTREVISTA_COM_FAMILIARES,
    ATENDIMENTO_ONLINE,
    ATENDIMENTO_PRESENCIAL,
    ATENDIMENTO_DOMICILIAR,
    SESSAO_DE_ENCERRAMENTO,
    RETORNO,
    OUTRO
    
    
}