/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaintegramind.View.Componentes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author guilh
 */
public class Container extends javax.swing.JPanel {

    private int borderRadius = 30; // Ajuste o tamanho do arredondamento aqui
    private Color shadowColor = null;
    private int shadowX = 0;
    private int shadowY = 0;
    private int shadowBlur = 0;

    /**
     * Creates new form Container
     */
    public Container() {

        initComponents();
        setOpaque(false); // Importante: desativa a opacidade padrão para o arredondamento funcionar
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        g2.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        );

        // ---------- SOMBRA COM BLUR ----------
        if (shadowColor != null) {
            for (int i = shadowBlur; i >= 1; i--) {
                int alpha = shadowColor.getAlpha() / (i + 1);

                g2.setColor(new Color(
                        shadowColor.getRed(),
                        shadowColor.getGreen(),
                        shadowColor.getBlue(),
                        alpha
                ));

                g2.fillRoundRect(
                        shadowX - i,
                        shadowY - i,
                        getWidth() - shadowX + (i * 2),
                        getHeight() - shadowY + (i * 2),
                        borderRadius,
                        borderRadius
                );
            }
        }
        // ---------- FUNDO DO CONTAINER ----------
        g2.setColor(getBackground());
        g2.fillRoundRect(
                0,
                0,
                getWidth() - shadowX,
                getHeight() - shadowY,
                borderRadius,
                borderRadius
        );

        g2.dispose();
    }

    // Getter e Setter caso queira mudar o arredondamento dinamicamente
    public int getBorderRadius() {
        return borderRadius;
    }

    public void setBorderRadius(int borderRadius) {
        this.borderRadius = borderRadius;
        repaint();
    }

    public void setShadow(Color color, int x, int y, int blur) {
        this.shadowColor = color;
        this.shadowX = x;
        this.shadowY = y;
        this.shadowBlur = blur;
        repaint();
    }

    // sombra padrão
    public void setShadow() {
        setShadow(new Color(0, 0, 0, 80), 4, 4, 8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(246, 245, 250));
        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
