/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaintegramind.View.Painel;

import com.mycompany.sistemaintegramind.Model.dao.impl.AgendamentoJPA;
import com.mycompany.sistemaintegramind.Model.dao.impl.PacienteJPA;
import java.awt.Color;
import java.math.BigDecimal;

/**
 *
 * @author Micro
 */
  

    public class PainelView extends javax.swing.JPanel {

        /**
         * Creates new form PainelView
         */
        public PainelView() {
            initComponents();
            container1.setCardStyle();
            container2.setCardStyle();
            container3.setCardStyle();
            container5.setCardStyle();
            container6.setCardStyle();
            container7.setCardStyle();
            container8.setCardStyle();

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        container7 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        container6 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        container8 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        container2 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        jLabel3 = new javax.swing.JLabel();
        lblTotalAgendamentosDoDia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        container1 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        jLabel5 = new javax.swing.JLabel();
        lblFaturamento = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        container5 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        jLabel7 = new javax.swing.JLabel();
        lblPendente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        container3 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        lblTotalPacientesSistema = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 251, 253));
        setMinimumSize(new java.awt.Dimension(2000, 370));
        setLayout(new java.awt.GridBagLayout());

        container7.setMinimumSize(new java.awt.Dimension(1000, 0));

        javax.swing.GroupLayout container7Layout = new javax.swing.GroupLayout(container7);
        container7.setLayout(container7Layout);
        container7Layout.setHorizontalGroup(
            container7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2032, Short.MAX_VALUE)
        );
        container7Layout.setVerticalGroup(
            container7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 40);
        add(container7, gridBagConstraints);

        container6.setMinimumSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout container6Layout = new javax.swing.GroupLayout(container6);
        container6.setLayout(container6Layout);
        container6Layout.setHorizontalGroup(
            container6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        container6Layout.setVerticalGroup(
            container6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 40, 5);
        add(container6, gridBagConstraints);

        container8.setMinimumSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout container8Layout = new javax.swing.GroupLayout(container8);
        container8.setLayout(container8Layout);
        container8Layout.setHorizontalGroup(
            container8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        container8Layout.setVerticalGroup(
            container8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 40, 40);
        add(container8, gridBagConstraints);

        container2.setMinimumSize(new java.awt.Dimension(200, 150));
        container2.setPreferredSize(new java.awt.Dimension(584, 65));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Hoje");

        lblTotalAgendamentosDoDia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalAgendamentosDoDia.setForeground(new java.awt.Color(0, 153, 51));
        lblTotalAgendamentosDoDia.setText("8");
        lblTotalAgendamentosDoDia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTotalAgendamentosDoDiaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendar (1) (1).png"))); // NOI18N

        javax.swing.GroupLayout container2Layout = new javax.swing.GroupLayout(container2);
        container2.setLayout(container2Layout);
        container2Layout.setHorizontalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(63, 63, 63)
                .addGroup(container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAgendamentosDoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        container2Layout.setVerticalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(container2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalAgendamentosDoDia)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        add(container2, gridBagConstraints);

        container1.setMinimumSize(new java.awt.Dimension(200, 150));
        container1.setPreferredSize(new java.awt.Dimension(584, 65));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Receita");

        lblFaturamento.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblFaturamento.setForeground(new java.awt.Color(0, 153, 51));
        lblFaturamento.setText("R$ 1.200");
        lblFaturamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblFaturamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/money-bag (1).png"))); // NOI18N

        javax.swing.GroupLayout container1Layout = new javax.swing.GroupLayout(container1);
        container1.setLayout(container1Layout);
        container1Layout.setHorizontalGroup(
            container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addGroup(container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5))
                    .addGroup(container1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        container1Layout.setVerticalGroup(
            container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(container1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFaturamento)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 5, 5, 5);
        add(container1, gridBagConstraints);

        container5.setMinimumSize(new java.awt.Dimension(200, 150));
        container5.setPreferredSize(new java.awt.Dimension(584, 65));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Pendentes");

        lblPendente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPendente.setForeground(new java.awt.Color(255, 51, 51));
        lblPendente.setText("2");
        lblPendente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblPendenteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alarm (1).png"))); // NOI18N

        javax.swing.GroupLayout container5Layout = new javax.swing.GroupLayout(container5);
        container5.setLayout(container5Layout);
        container5Layout.setHorizontalGroup(
            container5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addGap(66, 66, 66)
                .addGroup(container5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPendente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        container5Layout.setVerticalGroup(
            container5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(container5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(container5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPendente)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 40);
        add(container5, gridBagConstraints);

        container3.setMinimumSize(new java.awt.Dimension(200, 150));
        container3.setLayout(new java.awt.GridBagLayout());

        lblTotalPacientesSistema.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalPacientesSistema.setForeground(new java.awt.Color(0, 153, 51));
        lblTotalPacientesSistema.setText("127");
        lblTotalPacientesSistema.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTotalPacientesSistemaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container3.add(lblTotalPacientesSistema, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Pacientes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        container3.add(jLabel2, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-user (3) (2).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 60;
        container3.add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 40, 5, 5);
        add(container3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTotalPacientesSistemaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTotalPacientesSistemaAncestorAdded
        PacienteJPA pacientejpa = new PacienteJPA();
        int totalpacientes = pacientejpa.totalPacientesAtivos();
        String totalpacientesTexto = String.valueOf(totalpacientes);
        lblTotalPacientesSistema.setText(totalpacientesTexto);
    }//GEN-LAST:event_lblTotalPacientesSistemaAncestorAdded

    private void lblFaturamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblFaturamentoAncestorAdded
        AgendamentoJPA agendamentojpa = new AgendamentoJPA();
        BigDecimal faturamento = agendamentojpa.faturamento();

        //2026-09-24 Juliano: Verifica se o faturamento não é nulo para evitar erros
        if (faturamento == null) {
            faturamento = BigDecimal.ZERO;
        }

        //2026-09-24 Juliano: cria o formato da moeda brasileira
        java.text.NumberFormat nf = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt", "BR"));

        //2026-09-24 Juliano: Formata o BigDecimal (ele já adiciona o "R$" e ajusta os pontos e vírgulas)
        String faturamentoTexto = nf.format(faturamento);

        
        lblFaturamento.setText(faturamentoTexto);
    
    }//GEN-LAST:event_lblFaturamentoAncestorAdded

    private void lblPendenteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblPendenteAncestorAdded
        AgendamentoJPA agendamentojpa = new AgendamentoJPA();
        int agendamentosPendentes = agendamentojpa.totalPagamentosPendentes();
        String textoagendamentosPendentes = String.valueOf(agendamentosPendentes);
        lblPendente.setText(textoagendamentosPendentes);
    }//GEN-LAST:event_lblPendenteAncestorAdded

    private void lblTotalAgendamentosDoDiaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTotalAgendamentosDoDiaAncestorAdded
        AgendamentoJPA agendamentojpa = new AgendamentoJPA();
        int totalAgendamentosDoDia = agendamentojpa.totalAgendamentosDoDia();
        String totalAgendamentosDoDiaTexto = String.valueOf(totalAgendamentosDoDia);
        lblTotalAgendamentosDoDia.setText(totalAgendamentosDoDiaTexto);

    }//GEN-LAST:event_lblTotalAgendamentosDoDiaAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.sistemaintegramind.View.Componentes.Container container1;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container2;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container3;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container5;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container6;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container7;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFaturamento;
    private javax.swing.JLabel lblPendente;
    private javax.swing.JLabel lblTotalAgendamentosDoDia;
    private javax.swing.JLabel lblTotalPacientesSistema;
    // End of variables declaration//GEN-END:variables
}
