/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaintegramind.View.Painel;

import com.mycompany.sistemaintegramind.Model.dao.impl.AgendamentoJPA;
import com.mycompany.sistemaintegramind.Model.dao.impl.PacienteJPA;
import com.mycompany.sistemaintegramind.Model.entidades.Usuarios;
import com.mycompany.sistemaintegramind.View.Componentes.Container;
import com.mycompany.sistemaintegramind.util.Utilitarios.ImagemUtil;
import java.awt.Color;
import java.awt.Image;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.ImageIcon;

/**
 *
 * @author Micro
 */
public class PainelView extends javax.swing.JPanel {
    
    private Usuarios usuarioLogado;
    
    public PainelView(Usuarios usuariologado) {
        initComponents();
        this.usuarioLogado = usuariologado;
        lblUsuario.setText(usuariologado.getUsuario());
        
        container6.setCardStyle();
        container8.setCardStyle();
        container9.setCardStyle();
        
        Color PacienteBgColor = new Color(179, 255, 193);
        Color HojeBgColor = new Color(179, 218, 255);
        Color ReceitaBgColor = new Color(255, 237, 179);
        Color PendentesBgColor = new Color(255, 179, 184);

        // Paciente
        ImageIcon PacienteBgIcon = new ImageIcon(getClass().getResource("/imagens/PainelIcons/PacientesBgIcon.png"));
        Image PacienteBgIconRecolorido = ImagemUtil.recolorir(PacienteBgIcon.getImage(), PacienteBgColor);
        containerPacientes.setCardStyle(
                new Color(235, 250, 240), PacienteBgIconRecolorido,
                Container.Alignment.BOTTOM_RIGHT,
                180, 180, 60, 40
        );

        // Hoje
        ImageIcon HojeBgIcon = new ImageIcon(getClass().getResource("/imagens/PainelIcons/HojeBgIcon.png"));
        Image HojeBgIconRecolorido = ImagemUtil.recolorir(HojeBgIcon.getImage(), HojeBgColor);
        containerHoje.setCardStyle(
                new Color(238, 246, 255), HojeBgIconRecolorido,
                Container.Alignment.BOTTOM_RIGHT,
                160, 160, 60, 40
        );

        // Receita
        ImageIcon ReceitaBgIcon = new ImageIcon(getClass().getResource("/imagens/PainelIcons/ReceitaBgIcon.png"));
        Image ReceitaBgIconRecolorido = ImagemUtil.recolorir(ReceitaBgIcon.getImage(), ReceitaBgColor);
        containerReceita.setCardStyle(
                new Color(255, 249, 230), ReceitaBgIconRecolorido,
                Container.Alignment.BOTTOM_RIGHT,
                180, 180, 60, 40
        );

        // Pendentes
        ImageIcon PendentesBgIcon = new ImageIcon(getClass().getResource("/imagens/PainelIcons/PendentesBgIcon.png"));
        Image PendentesBgIconRecolorido = ImagemUtil.recolorir(PendentesBgIcon.getImage(), PendentesBgColor);
        containerPendentes.setCardStyle(
                new Color(255, 240, 240), PendentesBgIconRecolorido,
                Container.Alignment.BOTTOM_RIGHT,
                180, 180, 60, 40
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        circularIconLabelBeanInfo1 = new com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabelBeanInfo();
        container6 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        container8 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        containerHoje = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        jLabel3 = new javax.swing.JLabel();
        lblTotalAgendamentosDoDia = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        circularIconLabel3 = new com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel();
        containerReceita = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        jLabel5 = new javax.swing.JLabel();
        lblFaturamento = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        circularIconLabel4 = new com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel();
        containerPendentes = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        jLabel7 = new javax.swing.JLabel();
        lblPendente = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        circularIconLabel5 = new com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel();
        containerPacientes = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        lblTotalPacientesSistema = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        circularIconLabel2 = new com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        container4 = new com.mycompany.sistemaintegramind.View.Componentes.Container();
        jLabel4 = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblDataHoje = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        container9 = new com.mycompany.sistemaintegramind.View.Componentes.Container();

        setBackground(new java.awt.Color(251, 251, 253));
        setMinimumSize(new java.awt.Dimension(2000, 370));
        setLayout(new java.awt.GridBagLayout());

        container6.setMinimumSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout container6Layout = new javax.swing.GroupLayout(container6);
        container6.setLayout(container6Layout);
        container6Layout.setHorizontalGroup(
            container6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2207, Short.MAX_VALUE)
        );
        container6Layout.setVerticalGroup(
            container6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(container6, gridBagConstraints);

        container8.setMinimumSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout container8Layout = new javax.swing.GroupLayout(container8);
        container8.setLayout(container8Layout);
        container8Layout.setHorizontalGroup(
            container8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
        );
        container8Layout.setVerticalGroup(
            container8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(container8, gridBagConstraints);

        containerHoje.setMaximumSize(new java.awt.Dimension(0, 0));
        containerHoje.setMinimumSize(new java.awt.Dimension(200, 180));
        containerHoje.setPreferredSize(new java.awt.Dimension(319, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Hoje");

        lblTotalAgendamentosDoDia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalAgendamentosDoDia.setForeground(new java.awt.Color(7, 83, 159));
        lblTotalAgendamentosDoDia.setText("8");
        lblTotalAgendamentosDoDia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTotalAgendamentosDoDiaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(7, 83, 159));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/HojeIcon30x30.png"))); // NOI18N
        jLabel14.setText("Agendamentos do dia");

        circularIconLabel3.setBackground(new java.awt.Color(37, 91, 185));
        circularIconLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/HojeIconFull.png"))); // NOI18N
        circularIconLabel3.setIconColor(new java.awt.Color(232, 255, 255));
        circularIconLabel3.setIconHeight(55);
        circularIconLabel3.setIconWidth(55);
        circularIconLabel3.setShadowColor(new java.awt.Color(102, 102, 102));
        circularIconLabel3.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout containerHojeLayout = new javax.swing.GroupLayout(containerHoje);
        containerHoje.setLayout(containerHojeLayout);
        containerHojeLayout.setHorizontalGroup(
            containerHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHojeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(circularIconLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(containerHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerHojeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalAgendamentosDoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(containerHojeLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        containerHojeLayout.setVerticalGroup(
            containerHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHojeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalAgendamentosDoDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
            .addGroup(containerHojeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(circularIconLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(containerHoje, gridBagConstraints);

        containerReceita.setMaximumSize(new java.awt.Dimension(0, 0));
        containerReceita.setMinimumSize(new java.awt.Dimension(200, 180));
        containerReceita.setPreferredSize(new java.awt.Dimension(319, 200));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Receita");

        lblFaturamento.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblFaturamento.setForeground(new java.awt.Color(196, 131, 15));
        lblFaturamento.setText("R$ 1.200");
        lblFaturamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblFaturamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(196, 131, 15));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/ReceitaIcon30x30.png"))); // NOI18N
        jLabel17.setText("Total do mês");

        circularIconLabel4.setBackground(new java.awt.Color(172, 127, 2));
        circularIconLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/ReceitaIconFull.png"))); // NOI18N
        circularIconLabel4.setIconColor(new java.awt.Color(246, 227, 148));
        circularIconLabel4.setIconHeight(65);
        circularIconLabel4.setIconWidth(70);
        circularIconLabel4.setShadowColor(new java.awt.Color(102, 102, 102));
        circularIconLabel4.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout containerReceitaLayout = new javax.swing.GroupLayout(containerReceita);
        containerReceita.setLayout(containerReceitaLayout);
        containerReceitaLayout.setHorizontalGroup(
            containerReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerReceitaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(circularIconLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(containerReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerReceitaLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(122, 122, 122)))
        );
        containerReceitaLayout.setVerticalGroup(
            containerReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerReceitaLayout.createSequentialGroup()
                .addGroup(containerReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerReceitaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFaturamento))
                    .addGroup(containerReceitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(circularIconLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(containerReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerReceitaLayout.createSequentialGroup()
                    .addContainerGap(140, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(10, 10, 10)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(containerReceita, gridBagConstraints);

        containerPendentes.setMaximumSize(new java.awt.Dimension(0, 0));
        containerPendentes.setMinimumSize(new java.awt.Dimension(200, 180));
        containerPendentes.setPreferredSize(new java.awt.Dimension(319, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Pendentes");

        lblPendente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPendente.setForeground(new java.awt.Color(189, 0, 0));
        lblPendente.setText("2");
        lblPendente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblPendenteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(189, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/PendentesIcon30x30.png"))); // NOI18N
        jLabel16.setText("Formulários sem respostas");

        circularIconLabel5.setBackground(new java.awt.Color(213, 53, 77));
        circularIconLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/PendentesIconFull.png"))); // NOI18N
        circularIconLabel5.setIconColor(new java.awt.Color(255, 227, 227));
        circularIconLabel5.setIconHeight(60);
        circularIconLabel5.setIconWidth(60);
        circularIconLabel5.setShadowColor(new java.awt.Color(102, 102, 102));
        circularIconLabel5.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout containerPendentesLayout = new javax.swing.GroupLayout(containerPendentes);
        containerPendentes.setLayout(containerPendentesLayout);
        containerPendentesLayout.setHorizontalGroup(
            containerPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPendentesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(circularIconLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(containerPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblPendente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        containerPendentesLayout.setVerticalGroup(
            containerPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPendentesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(containerPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPendentesLayout.createSequentialGroup()
                        .addComponent(circularIconLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(containerPendentesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16))))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(containerPendentes, gridBagConstraints);

        containerPacientes.setMaximumSize(new java.awt.Dimension(0, 0));
        containerPacientes.setMinimumSize(new java.awt.Dimension(200, 180));
        containerPacientes.setPreferredSize(new java.awt.Dimension(319, 200));

        lblTotalPacientesSistema.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalPacientesSistema.setForeground(new java.awt.Color(2, 105, 16));
        lblTotalPacientesSistema.setText("127");
        lblTotalPacientesSistema.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblTotalPacientesSistemaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Pacientes");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 105, 16));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/PacientesIcon30x30.png"))); // NOI18N
        jLabel15.setText("Total de cadastros");

        circularIconLabel2.setBackground(new java.awt.Color(24, 159, 94));
        circularIconLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PainelIcons/PacientesIconFull.png"))); // NOI18N
        circularIconLabel2.setIconColor(new java.awt.Color(229, 255, 234));
        circularIconLabel2.setIconHeight(60);
        circularIconLabel2.setIconOffsetX(5);
        circularIconLabel2.setIconOffsetY(-1);
        circularIconLabel2.setIconWidth(60);
        circularIconLabel2.setShadowColor(new java.awt.Color(102, 102, 102));
        circularIconLabel2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout containerPacientesLayout = new javax.swing.GroupLayout(containerPacientes);
        containerPacientes.setLayout(containerPacientesLayout);
        containerPacientesLayout.setHorizontalGroup(
            containerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(circularIconLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalPacientesSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerPacientesLayout.setVerticalGroup(
            containerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(containerPacientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerPacientesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalPacientesSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(circularIconLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(containerPacientes, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 73, 32));
        jLabel6.setText("Olá,");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 73, 32));
        jLabel1.setText("Seja bem-vindo(a) ao IntegraMind!");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agendar.png"))); // NOI18N

        lblDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDia.setText("Terça");

        lblDataHoje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDataHoje.setText("30 de setembro de 2020");
        lblDataHoje.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblDataHojeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout container4Layout = new javax.swing.GroupLayout(container4);
        container4.setLayout(container4Layout);
        container4Layout.setHorizontalGroup(
            container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDia)
                    .addComponent(lblDataHoje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        container4Layout.setVerticalGroup(
            container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(container4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container4Layout.createSequentialGroup()
                        .addComponent(lblDataHoje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDia))
                    .addGroup(container4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(4, 73, 32));
        lblUsuario.setText("JULIANO ALESSANDRO DOS SANTOS");
        lblUsuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblUsuarioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1242, Short.MAX_VALUE)
                .addComponent(container4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(container4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jPanel1, gridBagConstraints);

        container9.setMinimumSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout container9Layout = new javax.swing.GroupLayout(container9);
        container9.setLayout(container9Layout);
        container9Layout.setHorizontalGroup(
            container9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        container9Layout.setVerticalGroup(
            container9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(container9, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTotalPacientesSistemaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTotalPacientesSistemaAncestorAdded
        PacienteJPA pacientejpa = new PacienteJPA();
        int totalpacientes = pacientejpa.totalPacientesAtivos();
        String totalpacientesTexto = String.valueOf(totalpacientes);
        lblTotalPacientesSistema.setText(totalpacientesTexto);
    }//GEN-LAST:event_lblTotalPacientesSistemaAncestorAdded

    private void lblFaturamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblFaturamentoAncestorAdded
        AgendamentoJPA agendamentojpa = new AgendamentoJPA();
        BigDecimal faturamento = agendamentojpa.faturamento();

        //2026-09-24 Juliano: Verifica se o faturamento não é nulo para evitar erros
        if (faturamento == null) {
            faturamento = BigDecimal.ZERO;
        }

        //2026-09-24 Juliano: cria o formato da moeda brasileira
        java.text.NumberFormat nf = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt", "BR"));

        //2026-09-24 Juliano: Formata o BigDecimal (ele já adiciona o "R$" e ajusta os pontos e vírgulas)
        String faturamentoTexto = nf.format(faturamento);
        
        lblFaturamento.setText(faturamentoTexto);

    }//GEN-LAST:event_lblFaturamentoAncestorAdded

    private void lblPendenteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblPendenteAncestorAdded
        AgendamentoJPA agendamentojpa = new AgendamentoJPA();
        int agendamentosPendentes = agendamentojpa.totalPagamentosPendentes();
        String textoagendamentosPendentes = String.valueOf(agendamentosPendentes);
        lblPendente.setText(textoagendamentosPendentes);
    }//GEN-LAST:event_lblPendenteAncestorAdded

    private void lblTotalAgendamentosDoDiaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTotalAgendamentosDoDiaAncestorAdded
        AgendamentoJPA agendamentojpa = new AgendamentoJPA();
        int totalAgendamentosDoDia = agendamentojpa.totalAgendamentosDoDia();
        String totalAgendamentosDoDiaTexto = String.valueOf(totalAgendamentosDoDia);
        lblTotalAgendamentosDoDia.setText(totalAgendamentosDoDiaTexto);
    }//GEN-LAST:event_lblTotalAgendamentosDoDiaAncestorAdded

    private void lblUsuarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblUsuarioAncestorAdded
     
    }//GEN-LAST:event_lblUsuarioAncestorAdded

    private void lblDataHojeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblDataHojeAncestorAdded
         lblDataHoje.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy", new Locale("pt", "BR"))));
         lblDia.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("EEEE", new Locale("pt", "BR"))));
    }//GEN-LAST:event_lblDataHojeAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel circularIconLabel2;
    private com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel circularIconLabel3;
    private com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel circularIconLabel4;
    private com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabel circularIconLabel5;
    private com.mycompany.sistemaintegramind.util.Utilitarios.CircularIconLabelBeanInfo circularIconLabelBeanInfo1;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container4;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container6;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container8;
    private com.mycompany.sistemaintegramind.View.Componentes.Container container9;
    private com.mycompany.sistemaintegramind.View.Componentes.Container containerHoje;
    private com.mycompany.sistemaintegramind.View.Componentes.Container containerPacientes;
    private com.mycompany.sistemaintegramind.View.Componentes.Container containerPendentes;
    private com.mycompany.sistemaintegramind.View.Componentes.Container containerReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDataHoje;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblFaturamento;
    private javax.swing.JLabel lblPendente;
    private javax.swing.JLabel lblTotalAgendamentosDoDia;
    private javax.swing.JLabel lblTotalPacientesSistema;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
